import { readFile } from "node:fs/promises";
import { access } from "node:fs/promises";
import {
  collectEnvInputSecrets,
  redactSecretEnvContent,
} from "./redact-secrets.js";
import {
  DEFAULT_HARNESS_CONFIG_PATH,
  type LocalFilePaths,
  type SetupEnvInput,
} from "./setup-state.js";

const SECRET_KEYS = [
  "LINEAR_API_KEY",
  "CURSOR_API_KEY",
  "GITHUB_TOKEN",
] as const;

const MANAGED_KEYS = ["HARNESS_CONFIG_PATH", ...SECRET_KEYS] as const;

export interface EnvKeyPresence {
  HARNESS_CONFIG_PATH: boolean;
  LINEAR_API_KEY: boolean;
  CURSOR_API_KEY: boolean;
  GITHUB_TOKEN: boolean;
}

export interface ParsedEnvFile {
  values: Record<string, string>;
  presence: EnvKeyPresence;
}

async function fileExists(filePath: string): Promise<boolean> {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

export function parseEnvFileContent(content: string): ParsedEnvFile {
  const values: Record<string, string> = {};
  const presence: EnvKeyPresence = {
    HARNESS_CONFIG_PATH: false,
    LINEAR_API_KEY: false,
    CURSOR_API_KEY: false,
    GITHUB_TOKEN: false,
  };

  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) {
      continue;
    }
    const separator = trimmed.indexOf("=");
    if (separator === -1) {
      continue;
    }
    const key = trimmed.slice(0, separator).trim();
    const value = trimmed.slice(separator + 1).trim();
    if (key in presence) {
      values[key] = value;
      if (value.length > 0) {
        presence[key as keyof EnvKeyPresence] = true;
      }
    }
  }

  return { values, presence };
}

export async function readExistingEnvFile(
  paths: LocalFilePaths,
): Promise<ParsedEnvFile | null> {
  if (!(await fileExists(paths.envLocal))) {
    return null;
  }
  const content = await readFile(paths.envLocal, "utf8");
  return parseEnvFileContent(content);
}

export function mergeEnvInput(
  existing: ParsedEnvFile | null,
  input: SetupEnvInput,
): SetupEnvInput {
  const merged: SetupEnvInput = {
    harnessConfigPath:
      input.harnessConfigPath?.trim() ||
      existing?.values.HARNESS_CONFIG_PATH ||
      DEFAULT_HARNESS_CONFIG_PATH,
  };

  const secretMap = {
    linearApiKey: "LINEAR_API_KEY",
    cursorApiKey: "CURSOR_API_KEY",
    githubToken: "GITHUB_TOKEN",
  } as const;

  for (const [inputKey, envKey] of Object.entries(secretMap)) {
    const submitted = input[inputKey as keyof typeof secretMap]?.trim();
    if (submitted) {
      merged[inputKey as keyof typeof secretMap] = submitted;
    } else if (existing?.values[envKey]) {
      merged[inputKey as keyof typeof secretMap] = existing.values[envKey];
    }
  }

  return merged;
}

function generateEnvHeader(): string {
  return `# Operator local setup — generated by harness setup core
# Do not commit .env.local (gitignored).

# --- Local private harness config (local only) ---
# Points at your structured target-repo config file.
# Edit .harness/config.local.json after init; keep this path unchanged.

# --- GitHub Actions only (cloud runs) — do NOT put in .env.local ---
# HARNESS_CONFIG_JSON_B64 replaces the whole harness config for that run.
# It is NOT an overlay with committed harness.config.json.
# Base64-encode your full .harness/config.local.json and set it as a
# GitHub Actions secret on the harness repo. Include every repo you want
# the harness to manage in repos[] and allowedTargetRepos[].

# --- Live automation API keys (local CLI) ---
# Fill these in .env.local for local doctor and harness runs.

# Local CLI name for GitHub API access (doctor merge profile, handoff, merge).
# In GitHub Actions the secret is named HARNESS_GITHUB_TOKEN (workflow maps it
# to runtime GITHUB_TOKEN). Do not use HARNESS_GITHUB_TOKEN in .env.local.
`;
}

export function generateMergedEnvContent(merged: SetupEnvInput): string {
  const harnessConfigPath =
    merged.harnessConfigPath ?? DEFAULT_HARNESS_CONFIG_PATH;
  const linearApiKey = merged.linearApiKey ?? "";
  const cursorApiKey = merged.cursorApiKey ?? "";
  const githubToken = merged.githubToken ?? "";

  return `${generateEnvHeader()}HARNESS_CONFIG_PATH=${harnessConfigPath}

LINEAR_API_KEY=${linearApiKey}
CURSOR_API_KEY=${cursorApiKey}
GITHUB_TOKEN=${githubToken}
`;
}

export function redactEnvContent(content: string): string {
  return redactSecretEnvContent(content);
}

export function collectMergedSecrets(merged: SetupEnvInput): string[] {
  return collectEnvInputSecrets(merged);
}

export function summarizeManagedKeyPresence(
  merged: SetupEnvInput,
): EnvKeyPresence {
  return {
    HARNESS_CONFIG_PATH: Boolean(merged.harnessConfigPath?.trim()),
    LINEAR_API_KEY: Boolean(merged.linearApiKey?.trim()),
    CURSOR_API_KEY: Boolean(merged.cursorApiKey?.trim()),
    GITHUB_TOKEN: Boolean(merged.githubToken?.trim()),
  };
}

export { MANAGED_KEYS };
