import { access, copyFile, readFile, writeFile } from "node:fs/promises";
import { SETUP_PERMISSIONS } from "./permission-model.js";
import type { SetupActionResult } from "./setup-actions.js";
import {
  DEFAULT_HARNESS_CONFIG_PATH,
  ENV_LOCAL,
  type LocalFilePaths,
  type SetupEnvInput,
  type SetupExecutionMode,
} from "./setup-state.js";

async function fileExists(filePath: string): Promise<boolean> {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

export interface WriteEnvLocalOptions {
  paths: LocalFilePaths;
  force?: boolean;
  mode?: SetupExecutionMode;
  input?: SetupEnvInput;
  content?: string;
}

export function generateEnvContent(input?: SetupEnvInput): string {
  const harnessConfigPath =
    input?.harnessConfigPath ?? DEFAULT_HARNESS_CONFIG_PATH;
  const linearApiKey = input?.linearApiKey ?? "";
  const cursorApiKey = input?.cursorApiKey ?? "";
  const githubToken = input?.githubToken ?? "";

  return `# Operator local setup — generated by harness setup core
# Do not commit .env.local (gitignored).

# --- Local private harness config (local only) ---
# Points at your structured target-repo config file.
# Edit .harness/config.local.json after init; keep this path unchanged.
HARNESS_CONFIG_PATH=${harnessConfigPath}

# --- GitHub Actions only (cloud runs) — do NOT put in .env.local ---
# HARNESS_CONFIG_JSON_B64 replaces the whole harness config for that run.
# It is NOT an overlay with committed harness.config.json.
# Base64-encode your full .harness/config.local.json and set it as a
# GitHub Actions secret on the harness repo. Include every repo you want
# the harness to manage in repos[] and allowedTargetRepos[].

# --- Live automation API keys (local CLI) ---
# Fill these in .env.local for local doctor and harness runs.
LINEAR_API_KEY=${linearApiKey}
CURSOR_API_KEY=${cursorApiKey}

# Local CLI name for GitHub API access (doctor merge profile, handoff, merge).
# In GitHub Actions the secret is named HARNESS_GITHUB_TOKEN (workflow maps it
# to runtime GITHUB_TOKEN). Do not use HARNESS_GITHUB_TOKEN in .env.local.
GITHUB_TOKEN=${githubToken}
`;
}

export async function readEnvExampleContent(
  paths: LocalFilePaths,
): Promise<string> {
  if (!(await fileExists(paths.envExample))) {
    throw new Error(`Missing source file: ${paths.envExample}`);
  }
  return readFile(paths.envExample, "utf8");
}

export async function scaffoldEnvFromExample(options: {
  paths: LocalFilePaths;
  force?: boolean;
  mode?: SetupExecutionMode;
}): Promise<SetupActionResult> {
  const { paths, force = false, mode = "apply" } = options;
  const label = ENV_LOCAL;
  const destExists = await fileExists(paths.envLocal);

  if (destExists && !force) {
    return {
      actionId: "scaffold-env-local",
      outcome: "skipped",
      targetPath: paths.envLocal,
      permission: SETUP_PERMISSIONS.localFileWrite,
      reason: "already exists",
      logMessage: `skipped ${label} (already exists)`,
    };
  }

  const content = await readEnvExampleContent(paths);

  if (mode === "dry-run") {
    return {
      actionId: "scaffold-env-local",
      outcome: destExists ? "wouldChange" : "preview",
      targetPath: paths.envLocal,
      content,
      permission: SETUP_PERMISSIONS.localFileWrite,
      reason: destExists ? "would overwrite with --force" : "would create",
      logMessage: destExists ? `would overwrite ${label}` : `would create ${label}`,
    };
  }

  await copyFile(paths.envExample, paths.envLocal);
  return {
    actionId: "scaffold-env-local",
    outcome: "changed",
    targetPath: paths.envLocal,
    content,
    permission: SETUP_PERMISSIONS.localFileWrite,
    reason: destExists ? "overwrote existing file" : "created new file",
    logMessage: `${destExists ? "overwrote" : "created"} ${label}`,
  };
}

export async function writeEnvLocal(
  options: WriteEnvLocalOptions,
): Promise<SetupActionResult> {
  const { paths, force = false, mode = "apply" } = options;
  const label = ENV_LOCAL;
  const destExists = await fileExists(paths.envLocal);

  if (destExists && !force) {
    return {
      actionId: "write-env-local",
      outcome: "skipped",
      targetPath: paths.envLocal,
      permission: SETUP_PERMISSIONS.localFileWrite,
      reason: "already exists",
      logMessage: `skipped ${label} (already exists)`,
    };
  }

  const content =
    options.content ?? generateEnvContent(options.input);

  if (mode === "dry-run") {
    return {
      actionId: "write-env-local",
      outcome: destExists ? "wouldChange" : "preview",
      targetPath: paths.envLocal,
      content,
      permission: SETUP_PERMISSIONS.localFileWrite,
      reason: destExists ? "would overwrite with --force" : "would create",
      logMessage: destExists ? `would overwrite ${label}` : `would create ${label}`,
    };
  }

  await writeFile(paths.envLocal, content, "utf8");
  return {
    actionId: "write-env-local",
    outcome: "changed",
    targetPath: paths.envLocal,
    content,
    permission: SETUP_PERMISSIONS.localFileWrite,
    reason: destExists ? "overwrote existing file" : "created new file",
    logMessage: `${destExists ? "overwrote" : "created"} ${label}`,
  };
}
